Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -24,7 +24,7 @@ jobs:
       - name: Install jsonnet
         run: sudo snap install jsonnet
           
-      - name: Run jsonnet, create, test and delete dashboard
+      - name: Run jsonnet
         env:
           INSTANA_BASE_URL: ${{ secrets.INSTANA_BASE_URL }}
           INSTANA_USER_ID: ${{ secrets.INSTANA_USER_ID }}
@@ -41,4 +41,13 @@ jobs:
         run: |
           DASHBOARD_ID=$(curl -s --request POST --url $INSTANA_BASE_URL/api/custom-dashboard --header "authorization: apiToken $INSTANA_API_TOKEN" --header 'content-type: application/json' --data @01-k8s-podlabel.json | jq -r .id)
           DASHBOARD_GET_HTTPCODE=$(curl -s -I -w "%{http_code}" -o /dev/null -H "authorization: apiToken $INSTANA_API_TOKEN" "$INSTANA_BASE_URL/api/custom-dashboard/$DASHBOARD_ID")
-          if [ $DASHBOARD_GET_HTTPCODE = 402 ]; then echo "Status 200. All good."; else echo "Error. Unexpected status code: $DASHBOARD_GET_HTTPCODE its not 200"; exit 1; fi
+          if [ $DASHBOARD_GET_HTTPCODE = 200 ]; then echo "Status 200. All good."; else echo "Error. Unexpected status code: $DASHBOARD_GET_HTTPCODE its not 200."; exit 1; fi
+
+      - name: Delete Dashboard
+        env:
+          INSTANA_BASE_URL: ${{ secrets.INSTANA_BASE_URL }}
+          INSTANA_USER_ID: ${{ secrets.INSTANA_USER_ID }}
+          INSTANA_API_TOKEN: ${{ secrets.INSTANA_API_TOKEN }}
+        run: |
+          DASHBOARD_GET_HTTPCODE=$(curl -s -I -w "%{http_code}" -o /dev/null -H "authorization: apiToken $INSTANA_API_TOKEN" "$INSTANA_BASE_URL/api/custom-dashboard/$DASHBOARD_ID")
+          if [ $DASHBOARD_GET_HTTPCODE = 200 ]; then echo "Status 200. All good."; else echo "Error. Unexpected status code: $DASHBOARD_GET_HTTPCODE its not 200."; exit 1; fi
