Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -42,4 +42,10 @@ jobs:
           DASHBOARD_ID=$(curl -s --request POST --url $INSTANA_BASE_URL/api/custom-dashboard --header "authorization: apiToken $INSTANA_API_TOKEN" --header 'content-type: application/json' --data @01-k8s-podlabel.json | jq -r .id)
           DASHBOARD_GET_HTTPCODE=$(curl -s -I -w "%{http_code}" -o /dev/null -H "authorization: apiToken $INSTANA_API_TOKEN" "$INSTANA_BASE_URL/api/custom-dashboard/$DASHBOARD_ID")
           echo $DASHBOARD_GET_HTTPCODE
-          test $DASHBOARD_GET_HTTPCODE==404
+          if test $DASHBOARD_GET_HTTPCODE==404; then
+            echo "Command succeeded"
+            exit 0
+          else
+            echo "Command failed"
+            exit 1
+          fi
