expecting 204

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -50,4 +50,4 @@ jobs:
         run: |
           curl -I -X "DELETE" -H "authorization: apiToken $INSTANA_API_TOKEN" "$INSTANA_BASE_URL/api/custom-dashboard/$DASHBOARD_ID"
           DASHBOARD_GET_HTTPCODE=$(curl -s -I -w "%{http_code}" -o /dev/null -H "authorization: apiToken $INSTANA_API_TOKEN" "$INSTANA_BASE_URL/api/custom-dashboard/$DASHBOARD_ID")
-          if [ $DASHBOARD_GET_HTTPCODE = 404 ]; then echo "Status 404. All good."; else echo "Error. Unexpected status code: $DASHBOARD_GET_HTTPCODE its not 404."; exit 1; fi
+          if [ $DASHBOARD_GET_HTTPCODE = 204 ]; then echo "Status 204. All good."; else echo "Error. Unexpected status code: $DASHBOARD_GET_HTTPCODE is not 204."; exit 1; fi
